version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      #      - ./src:/code
      - python-source:/src
    working_dir: /src
    tty: true
    # command: "/bin/bash"
    container_name: app

volumes:
  python-source:
    external: true

    # First start the container
    # docker-compose up -d

    # EDit file then run the python script
    # docker-compose exec app bash -c "python3 main.py"
